drop table PG560_JEE_TECHNOLOGY;

create table PG560_JEE_TECHNOLOGY(
	id integer generated by default as identity primary key,
	acronyms varchar(30) not null, 
	version varchar(30) not null, 
	jsr varchar(30) not null, 
	description varchar(300) not null
);

insert into PG560_JEE_TECHNOLOGY(acronyms, version, jsr, description) values('test','test','test','test');

insert into PG560_JEE_TECHNOLOGY(acronyms, version, jsr, description) values('test2','test2','test2','test2');
